"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.4
// source: model/ciphertext.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.EncodingMetadata = exports.CiphertextMetadata = exports.Ciphertext = exports.Encoding = exports.protobufPackage = void 0;
exports.encodingFromJSON = encodingFromJSON;
exports.encodingToJSON = encodingToJSON;
/* eslint-disable */
var wire_1 = require("@bufbuild/protobuf/wire");
exports.protobufPackage = "model.ciphertext";
/**
 * Enum for representing encoding types.
 * Can be extended for additional encoding support.
 */
var Encoding;
(function (Encoding) {
    Encoding[Encoding["ENCODING_UNSPECIFIED"] = 0] = "ENCODING_UNSPECIFIED";
    Encoding[Encoding["BASE_CONVERSION"] = 1] = "BASE_CONVERSION";
    Encoding[Encoding["ASCII"] = 2] = "ASCII";
    Encoding[Encoding["LATIN1"] = 3] = "LATIN1";
    Encoding[Encoding["UTF8"] = 4] = "UTF8";
    Encoding[Encoding["UTF16"] = 5] = "UTF16";
    Encoding[Encoding["UTF32"] = 6] = "UTF32";
    Encoding[Encoding["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(Encoding || (exports.Encoding = Encoding = {}));
function encodingFromJSON(object) {
    switch (object) {
        case 0:
        case "ENCODING_UNSPECIFIED":
            return Encoding.ENCODING_UNSPECIFIED;
        case 1:
        case "BASE_CONVERSION":
            return Encoding.BASE_CONVERSION;
        case 2:
        case "ASCII":
            return Encoding.ASCII;
        case 3:
        case "LATIN1":
            return Encoding.LATIN1;
        case 4:
        case "UTF8":
            return Encoding.UTF8;
        case 5:
        case "UTF16":
            return Encoding.UTF16;
        case 6:
        case "UTF32":
            return Encoding.UTF32;
        case -1:
        case "UNRECOGNIZED":
        default:
            return Encoding.UNRECOGNIZED;
    }
}
function encodingToJSON(object) {
    switch (object) {
        case Encoding.ENCODING_UNSPECIFIED:
            return "ENCODING_UNSPECIFIED";
        case Encoding.BASE_CONVERSION:
            return "BASE_CONVERSION";
        case Encoding.ASCII:
            return "ASCII";
        case Encoding.LATIN1:
            return "LATIN1";
        case Encoding.UTF8:
            return "UTF8";
        case Encoding.UTF16:
            return "UTF16";
        case Encoding.UTF32:
            return "UTF32";
        case Encoding.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
function createBaseCiphertext() {
    return { bytes: new Uint8Array(0), metadata: undefined };
}
exports.Ciphertext = {
    encode: function (message, writer) {
        if (writer === void 0) { writer = new wire_1.BinaryWriter(); }
        if (message.bytes.length !== 0) {
            writer.uint32(10).bytes(message.bytes);
        }
        if (message.metadata !== undefined) {
            exports.CiphertextMetadata.encode(message.metadata, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode: function (input, length) {
        var reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        var end = length === undefined ? reader.len : reader.pos + length;
        var message = createBaseCiphertext();
        while (reader.pos < end) {
            var tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.bytes = reader.bytes();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.metadata = exports.CiphertextMetadata.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON: function (object) {
        return {
            bytes: isSet(object.bytes) ? bytesFromBase64(object.bytes) : new Uint8Array(0),
            metadata: isSet(object.metadata) ? exports.CiphertextMetadata.fromJSON(object.metadata) : undefined,
        };
    },
    toJSON: function (message) {
        var obj = {};
        if (message.bytes.length !== 0) {
            obj.bytes = base64FromBytes(message.bytes);
        }
        if (message.metadata !== undefined) {
            obj.metadata = exports.CiphertextMetadata.toJSON(message.metadata);
        }
        return obj;
    },
    create: function (base) {
        return exports.Ciphertext.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial: function (object) {
        var _a;
        var message = createBaseCiphertext();
        message.bytes = (_a = object.bytes) !== null && _a !== void 0 ? _a : new Uint8Array(0);
        message.metadata = (object.metadata !== undefined && object.metadata !== null)
            ? exports.CiphertextMetadata.fromPartial(object.metadata)
            : undefined;
        return message;
    },
};
function createBaseCiphertextMetadata() {
    return { type: "", encoding: undefined };
}
exports.CiphertextMetadata = {
    encode: function (message, writer) {
        if (writer === void 0) { writer = new wire_1.BinaryWriter(); }
        if (message.type !== "") {
            writer.uint32(10).string(message.type);
        }
        if (message.encoding !== undefined) {
            exports.EncodingMetadata.encode(message.encoding, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode: function (input, length) {
        var reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        var end = length === undefined ? reader.len : reader.pos + length;
        var message = createBaseCiphertextMetadata();
        while (reader.pos < end) {
            var tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.type = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.encoding = exports.EncodingMetadata.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON: function (object) {
        return {
            type: isSet(object.type) ? globalThis.String(object.type) : "",
            encoding: isSet(object.encoding) ? exports.EncodingMetadata.fromJSON(object.encoding) : undefined,
        };
    },
    toJSON: function (message) {
        var obj = {};
        if (message.type !== "") {
            obj.type = message.type;
        }
        if (message.encoding !== undefined) {
            obj.encoding = exports.EncodingMetadata.toJSON(message.encoding);
        }
        return obj;
    },
    create: function (base) {
        return exports.CiphertextMetadata.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial: function (object) {
        var _a;
        var message = createBaseCiphertextMetadata();
        message.type = (_a = object.type) !== null && _a !== void 0 ? _a : "";
        message.encoding = (object.encoding !== undefined && object.encoding !== null)
            ? exports.EncodingMetadata.fromPartial(object.encoding)
            : undefined;
        return message;
    },
};
function createBaseEncodingMetadata() {
    return { encoding: 0, base: 0 };
}
exports.EncodingMetadata = {
    encode: function (message, writer) {
        if (writer === void 0) { writer = new wire_1.BinaryWriter(); }
        if (message.encoding !== 0) {
            writer.uint32(8).int32(message.encoding);
        }
        if (message.base !== 0) {
            writer.uint32(16).int32(message.base);
        }
        return writer;
    },
    decode: function (input, length) {
        var reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        var end = length === undefined ? reader.len : reader.pos + length;
        var message = createBaseEncodingMetadata();
        while (reader.pos < end) {
            var tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.encoding = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.base = reader.int32();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON: function (object) {
        return {
            encoding: isSet(object.encoding) ? encodingFromJSON(object.encoding) : 0,
            base: isSet(object.base) ? globalThis.Number(object.base) : 0,
        };
    },
    toJSON: function (message) {
        var obj = {};
        if (message.encoding !== 0) {
            obj.encoding = encodingToJSON(message.encoding);
        }
        if (message.base !== 0) {
            obj.base = Math.round(message.base);
        }
        return obj;
    },
    create: function (base) {
        return exports.EncodingMetadata.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial: function (object) {
        var _a, _b;
        var message = createBaseEncodingMetadata();
        message.encoding = (_a = object.encoding) !== null && _a !== void 0 ? _a : 0;
        message.base = (_b = object.base) !== null && _b !== void 0 ? _b : 0;
        return message;
    },
};
function bytesFromBase64(b64) {
    if (globalThis.Buffer) {
        return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
    }
    else {
        var bin = globalThis.atob(b64);
        var arr = new Uint8Array(bin.length);
        for (var i = 0; i < bin.length; ++i) {
            arr[i] = bin.charCodeAt(i);
        }
        return arr;
    }
}
function base64FromBytes(arr) {
    if (globalThis.Buffer) {
        return globalThis.Buffer.from(arr).toString("base64");
    }
    else {
        var bin_1 = [];
        arr.forEach(function (byte) {
            bin_1.push(globalThis.String.fromCharCode(byte));
        });
        return globalThis.btoa(bin_1.join(""));
    }
}
function isSet(value) {
    return value !== null && value !== undefined;
}
